
services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql_db_830
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
    ports:
      - "8830:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - weblab830
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_830
    platform: linux/amd64
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8831:80"
    depends_on:
      - db
    networks:
      - weblab830
    restart: always

networks:
  weblab830:
    driver: bridge

volumes:
  mysql_data:
    driver: local